name: Deploy


on:
  release:
    types: [created]

jobs:
  Deploy:
    name: Deploy to AppEngine
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with: 
        submodules: recursive
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GAE_EMAIL }}
        service_account_key: ${{ secrets.GAE_KEY }}
    - name: Deploy
      run: |
        echo "${{ secrets.SVC_CREDENTIALS }}" > ./credentials.json
        node ./deploy/generate --APP_URL=${{ secrets.APP_URL }} --DB_INSTANCE_CONNECTION=${{ secrets.DB_INSTANCE_CONNECTION }} --DB_CLIENT=${{ secrets.DB_CLIENT }} --DB_PORT=${{ secrets.DB_PORT }} --DB_USER=${{ secrets.DB_USER }} --DB_PASSWORD=${{ secrets.DB_PASSWORD }} --DB_NAME=${{ secrets.DB_NAME }} --GCS_BUCKET=${{ secrets.GCS_BUCKET }} --MAIL_USER=${{ secrets.MAIL_USER }} --MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
        yarn add ghost-v3-google-cloud-storage
        mkdir -p content/adapters/storage/gcs
        cp -R node_modules/ghost-v3-google-cloud-storage/* content/adapters/storage/gcs/
        gcloud app deploy app.yaml --project ${{ secrets.GAE_PROJECT }}
